development:
  adapter: postgresql
  database: db/development_doorshop
  pool: 5
  timeout: 5000
  username: andrey
  password: 12345

test:
  adapter: postgresql
  database: db/test_doorshop
  pool: 5
  timeout: 5000
  username: andrey
  password: 12345

production:
  adapter: postgresql
  database: db/production_doorshop
  pool: 5
  timeout: 5000
  username: andrey
  password: 12345
